### ISSUE TITLE
Index file

### ISSUE THREAD

**Issue by noahkoch** [opennebraska/api-localboards-org#7]
http://api.localboards.org shouldn't be a 404 page.

**Comment by trakaus** [comment]
How about redirecting to the /docs

**Comment by noahkoch** [comment]
Check out this sexy beast: http://api.localboards.org/

**Comment by trakaus** [comment]
She is almost sexy, add an (s) to board for the git hub link. :)

**Comment by noahkoch** [comment]
hahah sounds good

On Mon, Nov 25, 2013 at 11:48 PM, Ryan Walker notifications@github.comwrote:

> She is almost sexy, add an (s) to board for the git hub link. :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/noahkoch/api-localboards-org/issues/7#issuecomment-29269037
> .

## 

Noah Kochanowicz

"Somewhere, something incredible is waiting to be known."
-Carl Sagan
